### ISSUE TITLE
Where can I download the HWD+ dataset from

### ISSUE THREAD

**Issue by ariel415el** [thawro/yolov8-digits-detection#2]
I can't find a link to this dataset. Can you help?

**Comment by thawro** [comment]
Sure, here are the links:

Link to the citation from the paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9702948/#CR20
Link do google drive: https://drive.google.com/drive/folders/1f2o1kjXLvcxRgtmMMuDkA2PQ5Zato4Or

**Comment by thawro** [comment]
If everything's sorted out, feel free to close this issue ;) 

Thanks!
